function h(s){return s.replace(/#T#/g,"\x3c")}
const KNOWN=[{mint:"DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",name:"Bonk",sym:"BONK"},{mint:"EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",name:"dogwifhat",sym:"WIF"},{mint:"2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",name:"Pudgy Penguins",sym:"PENGU"},{mint:"7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",name:"Popcat",sym:"POPCAT"},{mint:"MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",name:"cat in a dogs world",sym:"MEW"},{mint:"ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82",name:"BOOK OF MEME",sym:"BOME"},{mint:"JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",name:"Jupiter",sym:"JUP"},{mint:"6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",name:"OFFICIAL TRUMP",sym:"TRUMP"}];
const db={get:(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const users=()=>{const u=db.get("alfa_users",[]);if(!u.length){u.push({user:"trader",pass:"desk2026"});db.set("alfa_users",u)}return u};
const session=()=>db.get("alfa_session",null);
const emptyBook=()=>({capital:10000,cash:10000,equity:10000,peak:10000,pos:[],trd:[],audit:[],bot:{on:false,runs:0,buys:0,sells:0,msg:"apagado"}});
const book=()=>Object.assign(emptyBook(),db.get("alfa_book_"+(session()?.user||"x"),null)||{});
const save=b=>db.set("alfa_book_"+session().user,b);
const money=n=>Number(n||0).toLocaleString("es-ES",{style:"currency",currency:"USD",maximumFractionDigits:2});
const compact=n=>{n=+n||0;return n>=1e6?"$"+(n/1e6).toFixed(1)+"M":n>=1e3?"$"+(n/1e3).toFixed(0)+"k":money(n)};
const pct=n=>n==null||Number.isNaN(+n)?"-":((+n>=0?"+":"")+(+n).toFixed(1)+"%");
const cls=n=>n==null?"":(+n>=0?"up":"down");
const ticket=b=>Math.max(6,Math.min(60,b.capital*0.007));
let loop=null,running=false;
function pickSol(pairs){return (pairs||[]).filter(p=>p.chainId==="solana"&&+p.priceUsd>0).sort((a,b)=>(b.liquidity?.usd||0)-(a.liquidity?.usd||0))[0]}
function auditPair(p,hint){const liq=p.liquidity?.usd||0,vol=p.volume?.h24||0,chg=p.priceChange?.h24,flags=[];if(liq<25000)flags.push({t:"liq baja"});else flags.push({t:"liq ok"});let score=36+Math.min(28,Math.log10(Math.max(liq,1))*5.4);if(liq<25000)score-=26;score=Math.max(1,Math.min(99,Math.round(score)));return {mint:hint?.mint||p.baseToken?.address,name:hint?.name||p.baseToken?.name||p.baseToken?.symbol,sym:hint?.sym||p.baseToken?.symbol,price:+p.priceUsd,liq,vol,chg,flags,score}}
async function studySolana(){const out=[],seen=new Set();const add=a=>{if(a&&a.mint&&!seen.has(a.mint)){seen.add(a.mint);out.push(a)}};try{const j=await fetch("https://api.dexscreener.com/latest/dex/tokens/"+KNOWN.map(x=>x.mint).join(",")).then(r=>r.json());for(const hint of KNOWN){const pair=pickSol((j.pairs||[]).filter(p=>p.baseToken&&p.baseToken.address===hint.mint));if(pair)add(auditPair(pair,hint))}}catch(e){}try{const s=await fetch("https://api.dexscreener.com/latest/dex/search?q=solana%20meme").then(r=>r.json());for(const pair of (s.pairs||[]).filter(p=>p.chainId==="solana").slice(0,12))add(auditPair(pair))}catch(e){}out.sort((a,b)=>b.score-a.score);return out.slice(0,20)}
function mark(b){b.equity=b.cash+b.pos.reduce((s,p)=>s+(p.qty*p.last),0);b.peak=Math.max(b.peak||b.capital,b.equity)}
function closePos(b,p,px,why){b.cash+=p.qty*px;b.bot.sells=(b.bot.sells||0)+1;b.trd.unshift({ts:Date.now(),side:"SELL",id:p.sym,why,px});b.pos=b.pos.filter(x=>x.mint!==p.mint)}
function openPos(b,a,usd){if(b.pos.some(p=>p.mint===a.mint)||b.cash<usd||usd<5||!a.price)return false;b.cash-=usd;b.pos.push({mint:a.mint,name:a.name,sym:a.sym,qty:usd/a.price,entry:a.price,last:a.price,pnl:0,pnlUsd:0});b.bot.buys=(b.bot.buys||0)+1;b.trd.unshift({ts:Date.now(),side:"BUY",id:a.sym,why:"meme · "+money(usd),px:a.price});return true}
async function cycle(kind){if(running)return;running=true;const app=document.getElementById("app");const refresh=document.getElementById("refresh");app.classList.add("busy");if(refresh)refresh.classList.add("spin");try{const b=book();const audit=await studySolana();b.audit=audit;const byMint=Object.fromEntries(audit.map(a=>[a.mint,a]));b.pos.forEach(p=>{const q=byMint[p.mint];if(!q)return;p.last=q.price;p.pnl=((p.last-p.entry)/p.entry)*100;p.pnlUsd=(p.last-p.entry)*p.qty});let sold=0,bought=0;if(b.bot.on||kind==="burst"){b.pos.slice().forEach(p=>{if(p.pnl<=-7){closePos(b,p,p.last,"stop -7%");sold++}else if(p.pnl>=10){closePos(b,p,p.last,"take +10%");sold++}});const rotate=b.pos.slice().sort((a,c)=>a.pnl-c.pnl);const needSell=Math.max(1,1+Math.floor(Math.random()*2));for(const p of rotate){if(sold>=needSell)break;closePos(b,p,p.last,"rotacion paper");sold++}const playable=audit.filter(a=>a.score>=40&&a.liq>=15000&&a.price>0&&!b.pos.some(p=>p.mint===a.mint));const pool=playable.length?playable:audit.filter(x=>x.price>0);const size=ticket(b);const target=kind==="burst"?4+Math.floor(Math.random()*4):1+Math.floor(Math.random()*3);for(const a of pool){if(bought>=target||b.pos.length>=8)break;const usd=Math.min(size*(0.6+Math.random()*0.7),b.cash*0.12);if(openPos(b,a,usd))bought++}b.bot.runs+=1;b.bot.msg="ciclo "+b.bot.runs}mark(b);save(b);render()}finally{running=false;app.classList.remove("busy");if(refresh)refresh.classList.remove("spin")}}
function startLoop(){stopLoop();loop=setInterval(()=>{if(session()&&book().bot.on)cycle("tick")},18000)}
function stopLoop(){if(loop){clearInterval(loop);loop=null}}
const ring=s=>s>=70?"okbg":s>=50?"midbg":"badbg";
function render(){const s=session();document.getElementById("auth").classList.toggle("hidden",!!s);document.getElementById("app").classList.toggle("hidden",!s);if(!s)return;const b=book();mark(b);document.getElementById("equity").textContent=money(b.equity);document.getElementById("statusPill").textContent=b.bot.on?"EN BUCLE":"APAGADO";document.getElementById("flowPill").textContent=(b.bot.buys||0)+" compras · "+(b.bot.sells||0)+" ventas";document.getElementById("power").checked=!!b.bot.on;document.getElementById("powerLabel").textContent=b.bot.on?"Alfa operando":"Alfa parado";document.getElementById("powerHint").textContent=b.bot.on?"Compra y vende cada ~18s":"Enciende para operar sin parar";document.getElementById("liveDot").textContent=b.bot.on?"LIVE PAPER":"PAPER";document.getElementById("cap").value=b.capital;document.getElementById("ticket").textContent=money(ticket(b));document.getElementById("cash").textContent=money(b.cash);document.getElementById("npos").textContent=b.pos.length;document.getElementById("runs").textContent=b.bot.runs;document.getElementById("auditMeta").textContent=b.audit.length?b.audit.length+" memecoins Solana":"Sin datos";document.getElementById("auditList").innerHTML=b.audit.length?b.audit.map(a=>h("#T#div class=\"token\">#T#div class=\"ring "+ring(a.score)+"\">"+a.score+"#T#/div>#T#div class=\"meta\">#T#div class=\"name\">"+(a.name||a.sym)+"#T#/div>#T#div class=\"sym\">"+(a.sym||"")+"#T#/div>#T#/div>#T#div class=\"px\">#T#b>"+(a.price>=1?money(a.price):("$"+Number(a.price).toPrecision(3)))+"#T#/b>#T#span class=\""+cls(a.chg)+"\">"+pct(a.chg)+"#T#/span>#T#/div>#T#/div>")).join(""):h("#T#div class=\"empty\">Pulsa actualizar.#T#/div>");document.getElementById("pos").innerHTML=b.pos.length?b.pos.map(p=>h("#T#div class=\"token\">#T#div class=\"meta\">#T#div class=\"name\">"+p.name+"#T#/div>#T#/div>#T#div class=\"px "+cls(p.pnlUsd)+"\">#T#b>"+money(p.pnlUsd)+"#T#/b>#T#span>"+pct(p.pnl)+"#T#/span>#T#/div>#T#/div>")).join(""):h("#T#div class=\"empty\">Sin posiciones.#T#/div>");document.getElementById("log").innerHTML=b.trd.length?b.trd.slice(0,40).map(t=>h("#T#div class=\"log\">#T#b class=\""+(t.side==="BUY"?"up":"down")+"\">"+t.side+"#T#/b> "+t.id+" · "+t.why+"#T#/div>")).join(""):h("#T#div class=\"empty\">Sin actividad.#T#/div>")}
function login(user,pass){const u=users().find(x=>x.user===user&&x.pass===pass);if(!u)throw new Error("Usuario o password incorrectos");db.set("alfa_session",{user,at:Date.now()});render();cycle("refresh");if(book().bot.on)startLoop()}
document.getElementById("go").onclick=()=>{const f=new FormData(document.getElementById("form"));try{login(String(f.get("user")).trim().toLowerCase(),String(f.get("pass")))}catch(e){document.getElementById("err").textContent=e.message}};
document.getElementById("form").onsubmit=e=>{e.preventDefault();document.getElementById("go").click()};
document.getElementById("reg").onclick=()=>{const f=new FormData(document.getElementById("form"));const user=String(f.get("user")).trim().toLowerCase(),pass=String(f.get("pass"));if(user.length<3||pass.length<4){document.getElementById("err").textContent="Demasiado corto";return}const list=users();if(list.some(x=>x.user===user)){document.getElementById("err").textContent="Ese usuario ya existe";return}list.push({user,pass});db.set("alfa_users",list);login(user,pass)};
document.getElementById("out").onclick=()=>{stopLoop();localStorage.removeItem("alfa_session");location.reload()};
function saveCap(){const b=book();const n=Math.max(100,Number(document.getElementById("cap").value)||b.capital);const used=b.pos.reduce((s,p)=>s+p.entry*p.qty,0);b.capital=n;b.cash=Math.max(0,n-used);mark(b);save(b);render()}
document.getElementById("cap").onchange=saveCap;document.getElementById("cap").onblur=saveCap;
document.getElementById("power").onchange=async e=>{const b=book();b.bot.on=e.target.checked;save(b);render();if(b.bot.on){startLoop();await cycle("burst")}else stopLoop()};
function goRefresh(){cycle(book().bot.on?"tick":"refresh")}
document.getElementById("refresh").onclick=goRefresh;document.getElementById("refresh2").onclick=goRefresh;
document.querySelector(".tabbar").onclick=ev=>{const btn=ev.target.closest("button[data-pane]");if(!btn)return;document.querySelectorAll(".tabbar button[data-pane]").forEach(p=>p.classList.toggle("on",p===btn));document.querySelectorAll(".pane").forEach(p=>p.classList.toggle("on",p.dataset.pane===btn.dataset.pane))};
users();if(session()){render();cycle("refresh");if(book().bot.on)startLoop()}
