function vibeAlpha(row){var mom=row.fm||0;var last=row.hist||[];var sum=0;for(var i=0;i<last.length;i++)sum+=last[i];var mean=last.length?sum/last.length:row.price;var rev=mean?((row.price-mean)/mean)*100:0;row.rev=rev;row.vibe=Math.max(0,Math.min(100,Math.round(50+mom*8-Math.abs(rev)*1.5)));}
function tauricDesk(row){var tech=(row.fm||0)>0.25?1:(row.fm||0)<-0.25?-1:0;var sent=(row.vibe||50)>=55?1:(row.vibe||50)<=45?-1:0;var score=tech+sent;var risk=Math.abs(row.fm||0)>2.5?"HIGH":"OK";var trader=score>=1&&risk==="OK"?"BUY":score<=-1?"SELL":"HOLD";row.tauric=(trader==="BUY"&&risk==="OK")?"BUY":trader;row.risk=risk;row.bull=score>=1;row.bear=score<=-1;}
if(typeof study==="function"){var _study=study;study=function(){var list=_study();list.forEach(function(r){vibeAlpha(r);tauricDesk(r)});return list};}
if(typeof tradeTick==="function"){var _tick=tradeTick;tradeTick=function(b,audit,n){var buys=audit.filter(function(a){return a.price>0&&a.risk!=="HIGH"&&(a.tauric==="BUY"||a.jev==="BUY")});if(!buys.length)buys=audit.filter(function(a){return a.price>0});for(var i=0;i<n;i++){b.pos.forEach(edgeMark);var winners=b.pos.filter(function(p){return p.pnl>=0.5});var losers=b.pos.filter(function(p){return p.pnl<=-0.8});var pick=winners[0]||losers[0]||b.pos[0];if(pick)closePos(b,pick,pick.last,pick.pnl>=0?"PM take":"risk corte");var pool=buys.filter(function(a){return !b.pos.some(function(p){return p.mint===a.mint})});if(pool.length)openPos(b,pool[i%pool.length],Math.min(ticket(b),Math.max(10,b.cash*0.08)))}};
}
if(typeof openPos==="function"){var _open=openPos;openPos=function(b,a,usd){var ok=_open(b,a,usd);if(ok&&b.trd[0])b.trd[0].why=(a.cls||"mkt")+" · Vibe "+(a.vibe||0)+" · Tauric "+(a.tauric||"-");return ok};
}
if(typeof render==="function"){var _render=render;render=function(){_render();var list=(typeof book==="function"&&book().audit)||[];document.querySelectorAll("#auditList .token").forEach(function(el,i){var a=list[i];if(!a)return;var tag=el.querySelector(".tag");if(tag)tag.textContent=(a.cls||"")+" · Vibe "+(a.vibe||0)+" · "+(a.tauric||"-")+" · "+(a.risk||"");});var hint=document.getElementById("powerHint");if(hint&&typeof book==="function"&&book().bot.on)hint.textContent="Vibe+Tauric paper · 1 buy + 1 sell / 5s";};
}
