function liveCfg(){try{return Object.assign({pk:"",ticket:25,dd:3,ops:40,armed:false,tgToken:"",tgChat:""},JSON.parse(localStorage.getItem("alfa_live")||"{}"))}catch(e){return {pk:"",ticket:25,dd:3,ops:40,armed:false,tgToken:"",tgChat:""}}}
function saveLive(c){localStorage.setItem("alfa_live",JSON.stringify(c))}
function shortPk(pk){if(!pk)return "-";return pk.slice(0,4)+"..."+pk.slice(-4)}
function renderWallet(){var c=liveCfg();var st=document.getElementById("walletStatus");var pk=document.getElementById("walletPk");if(!st)return;st.textContent=c.pk?("Wallet lista · "+shortPk(c.pk)+" · LIVE LOCK"):"Sin wallet · LIVE LOCK";if(pk)pk.textContent=c.pk||"-";var t=document.getElementById("liveTicket");if(t)t.value=c.ticket;var d=document.getElementById("liveDd");if(d)d.value=c.dd;var o=document.getElementById("liveOps");if(o)o.value=c.ops}
async function connectPhantom(){var err=document.getElementById("liveErr");try{var provider=window.solana||(window.phantom&&window.phantom.solana);if(!provider||!provider.isPhantom){if(err)err.textContent="Instala Phantom o abre esta pagina en Phantom.";window.open("https://phantom.app/","_blank");return}var res=await provider.connect();var c=liveCfg();c.pk=String(res.publicKey);c.armed=false;saveLive(c);renderWallet();if(err)err.textContent="Pubkey guardada. LIVE bloqueado."}catch(e){if(err)err.textContent=e.message||"Cancelado"}}
function disconnectWallet(){var c=liveCfg();c.pk="";c.armed=false;saveLive(c);renderWallet();try{if(window.solana&&window.solana.disconnect)window.solana.disconnect()}catch(e){}}
function persistLimits(){var c=liveCfg();c.ticket=Math.max(5,Number(document.getElementById("liveTicket").value)||25);c.dd=Math.max(1,Math.min(20,Number(document.getElementById("liveDd").value)||3));c.ops=Math.max(1,Math.min(80,Number(document.getElementById("liveOps").value)||40));saveLive(c)}
document.getElementById("connectWallet").onclick=connectPhantom;
document.getElementById("disconnectWallet").onclick=disconnectWallet;
["liveTicket","liveDd","liveOps"].forEach(function(id){var el=document.getElementById(id);if(el){el.onchange=persistLimits;el.onblur=persistLimits}});
document.getElementById("armLive").onclick=function(){var err=document.getElementById("liveErr");if(!liveCfg().pk){err.textContent="Conecta Phantom primero.";return}err.textContent="LIVE bloqueado. Automatico = servidor + hot wallet. No pegues la seed."};
function renderTg(){var c=liveCfg();var t=document.getElementById("tgToken");var h=document.getElementById("tgChat");if(t&&document.activeElement!==t)t.value=c.tgToken||"";if(h&&document.activeElement!==h)h.value=c.tgChat||""}
function saveTg(){var c=liveCfg();var t=document.getElementById("tgToken");var h=document.getElementById("tgChat");c.tgToken=t?String(t.value).trim():"";c.tgChat=h?String(h.value).trim():"";saveLive(c);var err=document.getElementById("tgErr");if(err)err.textContent=c.tgToken&&c.tgChat?"Avisos guardados.":"Falta token o chat id."}
async function testTg(){saveTg();var c=liveCfg();var err=document.getElementById("tgErr");if(!c.tgToken||!c.tgChat){if(err)err.textContent="Guarda token y chat id.";return}try{var res=await fetch("https://api.telegram.org/bot"+c.tgToken+"/sendMessage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:c.tgChat,text:"Alfa paper: aviso de prueba. LIVE LOCK."})});var j=await res.json();if(err)err.textContent=j.ok?"Telegram OK":("Telegram: "+(j.description||"error"))}catch(e){if(err)err.textContent=e.message||"Error Telegram"}}
var stg=document.getElementById("saveTg");if(stg)stg.onclick=saveTg;var ttg=document.getElementById("testTg");if(ttg)ttg.onclick=testTg;
renderWallet();renderTg();
