function liveCfg(){try{return Object.assign({pk:"",ticket:25,dd:3,ops:40,armed:false,tgToken:"",tgChat:""},JSON.parse(localStorage.getItem("alfa_live")||"{}"))}catch(e){return {pk:"",ticket:25,dd:3,ops:40,armed:false,tgToken:"",tgChat:""}}}
function saveLive(c){localStorage.setItem("alfa_live",JSON.stringify(c))}
function shortPk(pk){if(!pk)return "-";return pk.slice(0,4)+"..."+pk.slice(-4)}
function provider(){return window.phantom&&window.phantom.solana||window.solana||null}
function renderWallet(){var c=liveCfg();var st=document.getElementById("walletStatus");var pk=document.getElementById("walletPk");if(!st)return;st.textContent=c.pk?("Wallet lista · "+shortPk(c.pk)+" · LIVE LOCK"):"Sin wallet · abre Alfa DENTRO de Phantom";if(pk)pk.textContent=c.pk||"-";var t=document.getElementById("liveTicket");if(t)t.value=c.ticket;var d=document.getElementById("liveDd");if(d)d.value=c.dd;var o=document.getElementById("liveOps");if(o)o.value=c.ops}
function phantomBrowseUrl(){var page=location.href.split("#")[0];return "https://phantom.app/ul/browse/"+encodeURIComponent(page)+"?ref="+encodeURIComponent(location.origin)}
async function tryConnect(silent){var err=document.getElementById("liveErr");var p=provider();if(!p||!p.isPhantom){if(!silent&&err)err.textContent="Phantom no esta inyectado. Abre esta URL en el navegador de Phantom (icono Explorar / Browse).";return false}try{var res=await p.connect({onlyIfTrusted:!!silent});var c=liveCfg();c.pk=String(res.publicKey);c.armed=false;saveLive(c);renderWallet();if(err)err.textContent="Phantom conectado. LIVE sigue bloqueado.";return true}catch(e){if(!silent&&err)err.textContent=e.message||"Conexion cancelada";return false}}
function connectPhantom(){var err=document.getElementById("liveErr");var p=provider();if(p&&p.isPhantom){tryConnect(false);return}if(err)err.textContent="Abriendo Phantom... luego pulsa Conectar otra vez DENTRO de la app.";location.href=phantomBrowseUrl()}
function saveManualPk(){var inp=document.getElementById("manualPk");var err=document.getElementById("liveErr");if(!inp)return;var v=String(inp.value||"").trim();if(v.length<32){if(err)err.textContent="Pega la direccion publica (pubkey), no la seed.";return}if(/\s/.test(v)||v.split(" ").length>=8){if(err)err.textContent="Eso parece una seed. Solo pubkey.";return}var c=liveCfg();c.pk=v;c.armed=false;saveLive(c);renderWallet();if(err)err.textContent="Pubkey guardada a mano. LIVE bloqueado."}
document.getElementById("connectWallet").onclick=connectPhantom;
var ow=document.getElementById("openInPhantom");if(ow)ow.onclick=function(){location.href=phantomBrowseUrl()};
var sm=document.getElementById("saveManualPk");if(sm)sm.onclick=saveManualPk;
document.getElementById("disconnectWallet").onclick=function(){var c=liveCfg();c.pk="";c.armed=false;saveLive(c);renderWallet();try{var p=provider();if(p&&p.disconnect)p.disconnect()}catch(e){}};
function persistLimits(){var c=liveCfg();c.ticket=Math.max(5,Number(document.getElementById("liveTicket").value)||25);c.dd=Math.max(1,Math.min(20,Number(document.getElementById("liveDd").value)||3));c.ops=Math.max(1,Math.min(80,Number(document.getElementById("liveOps").value)||40));saveLive(c)}
["liveTicket","liveDd","liveOps"].forEach(function(id){var el=document.getElementById(id);if(el){el.onchange=persistLimits;el.onblur=persistLimits}});
document.getElementById("armLive").onclick=function(){var err=document.getElementById("liveErr");if(!liveCfg().pk){err.textContent="Conecta o pega pubkey primero.";return}err.textContent="LIVE bloqueado. Automatico = servidor."};
function saveTg(){var c=liveCfg();var t=document.getElementById("tgToken");var h=document.getElementById("tgChat");c.tgToken=t?String(t.value).trim():"";c.tgChat=h?String(h.value).trim():"";saveLive(c);var err=document.getElementById("tgErr");if(err)err.textContent=c.tgToken&&c.tgChat?"Avisos guardados.":"Falta token o chat id."}
async function testTg(){saveTg();var c=liveCfg();var err=document.getElementById("tgErr");if(!c.tgToken||!c.tgChat){if(err)err.textContent="Guarda token y chat id.";return}try{var res=await fetch("https://api.telegram.org/bot"+c.tgToken+"/sendMessage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:c.tgChat,text:"Alfa paper: aviso de prueba."})});var j=await res.json();if(err)err.textContent=j.ok?"Telegram OK":("Telegram: "+(j.description||"error"))}catch(e){if(err)err.textContent=e.message}}
var stg=document.getElementById("saveTg");if(stg)stg.onclick=saveTg;var ttg=document.getElementById("testTg");if(ttg)ttg.onclick=testTg;
renderWallet();
tryConnect(true);
window.addEventListener("load",function(){setTimeout(function(){tryConnect(true)},400)});
